---
# Boxes from http://puppet-vagrant-boxes.puppetlabs.com/
# Updated: 2014-09-16
boxes:
  # VMWare
  'fedora-18-x64-vf503-nocm': 'http://puppet-vagrant-boxes.puppetlabs.com/fedora-18-x64-vf503-nocm.box'
  'centos-64-x64-fusion503-nocm': 'http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-fusion503-nocm.box'
  'debian-607-x64-vf503-nocm': 'http://puppet-vagrant-boxes.puppetlabs.com/debian-607-x64-vf503-nocm.box'
  'debian-70rc1-x64-vf503-nocm': 'http://puppet-vagrant-boxes.puppetlabs.com/debian-70rc1-x64-vf503-nocm.box'
  'ubuntu-server-10044-x64-fusion503-nocm': 'http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-10044-x64-fusion503-nocm.box'
  'ubuntu-svr-12042-x64-vf503-nocm': 'http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-svr-12042-x64-vf503-nocm.box'
  'fedora-18-x64-vbox4210-nocm': 'http://puppet-vagrant-boxes.puppetlabs.com/fedora-18-x64-vbox4210-nocm.box'

  # Built against VirtualBox 4.3.6
  'centos-65-x64-virtualbox-nocm': 'http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-nocm.box'
  'centos-510-x64-virtualbox-nocm': 'http://puppet-vagrant-boxes.puppetlabs.com/centos-510-x64-virtualbox-nocm.box'
  'debian-73-x64-virtualbox-nocm': 'http://puppet-vagrant-boxes.puppetlabs.com/debian-73-x64-virtualbox-nocm.box'
  'ubuntu-1310-x64-virtualbox-nocm': 'http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-1310-x64-virtualbox-nocm.box'

  # Built against VirtualBox 4.2.10 --- still work reliably with 4.3.x
  'fedora-18-x64-vbox4210-nocm': 'http://puppet-vagrant-boxes.puppetlabs.com/fedora-18-x64-vbox4210-nocm.box'
  'centos-64-x64-vbox4210-nocm': 'http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210-nocm.box'
  'centos-59-x64-vbox4210-nocm': 'http://puppet-vagrant-boxes.puppetlabs.com/centos-59-x64-vbox4210-nocm.box'
  'debian-607-x64-vbox4210-nocm': 'http://puppet-vagrant-boxes.puppetlabs.com/debian-607-x64-vbox4210-nocm.box'
  'debian-70rc1-x64-vbox4210-nocm': 'http://puppet-vagrant-boxes.puppetlabs.com/debian-70rc1-x64-vbox4210-nocm.box'
  'sles-11sp1-x64-vbox4210-nocm': 'http://puppet-vagrant-boxes.puppetlabs.com/sles-11sp1-x64-vbox4210-nocm.box'
  'ubuntu-server-10044-x64-vbox4210-nocm': 'http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-10044-x64-vbox4210-nocm.box'
  'ubuntu-server-12042-x64-vbox4210-nocm': 'http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box'

  # rob 2012r2 VirtualBox 4.2.16 box
  'win2012r2-x64-vbox4216-nocm': 'https://s3-us-west-1.amazonaws.com/ebrown-temp/win2012r2-x64-vbox4216-nocm.box'
  # charlies rebaked version of the above with newer guest additions / rdp enabled
  'win2012r2-x64-virtualbox-nocm': 'https://s3.amazonaws.com/sharpsteen-files/win2012r2-x64-virtualbox-nocm.box'
  # ethan 2012r2 VirtualBox 4.3.16 box based on Joe Fitzgerald packer templates
  # the SSH client here is awful, and PE doesn't install properly
  # 'win2012r2-x64-vbox4316-nocm': 'https://s3-us-west-1.amazonaws.com/ebrown-temp/win2012r2-x64-vbox4316-nocm.box'
