---
vms:
    # BUG: this must be 'master' based on how pe_build configures agents puppet.conf on Windows
  - name: master
    # this must be 'master' or else PE install may fail depending on network
    hostname: master
    box: centos-65-x64-virtualbox-nocm
    roles:
    # notes that roles are run in reverse order... because
    - pe-puppet-master
    - pe-forward-console
    - el-stop-firewall
    - el-fix-path
    - base
    - 1gb-memory
  - name: win2012-web-agent
    # hostname must not be a FQDN or the rename fails on Windows
    hostname: win2012-web-agent
    box: win2012r2-x64-virtualbox-nocm
    box_download_checksum_type: md5
    box_download_checksum: 63b8d3fdde5b7f5190dd937ea7897971
    roles:
    - pe-puppet-windows-web
    - windows
    - base
    - 2gb-memory
  # - name: win2012-sql-agent
  #   hostname: win2012-sql-agent
  #   box: win2012r2-x64-virtualbox-nocm
  #   roles:
  #   - pe-puppet-windows-sql
  #   - windows
  #   - base
  #   - 2gb-memory

roles:
  # our actual node specific stuff!
  pe-puppet-master:
    provisioners:
      # pe_bootstrap enables pluginsync and auto certificate signing
      - {type: pe_bootstrap, role: !ruby/sym master}
      - {type: shell, inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf" }
      - {type: shell, path: './config/setup-master.sh' }
  pe-puppet-windows-web:
    forwarded_ports:
      - {guest: 80, host: 8080, auto_correct: true}
    provisioners:
      - {type: pe_bootstrap}
      - {type: file, source: './facts/web_role.txt', destination: 'C:/ProgramData/PuppetLabs/facter/facts.d/web_role.txt'}
      - {type: shell, path: './config/setup-agent.ps1'}
  pe-puppet-windows-sql:
    provisioners:
      - {type: pe_bootstrap}
      - {type: file, source: './facts/database_role.txt', destination: 'C:/ProgramData/PuppetLabs/facter/facts.d/database_role.txt'}
      - {type: shell, path: './config/setup-agent.ps1'}

  # custom role definitions from puppet-debugging-kit
  base:
    private_networks:
      - {auto_network: true}
    provisioners:
      - {type: hosts}
  el-stop-firewall:
    provisioners:
      - type: shell
        inline: |
          service iptables stop
          chkconfig iptables off
  # Adds /usr/local/bin to the PATH
  el-fix-path:
    provisioners:
      - type: shell
        inline: |
          echo "export PATH=$PATH:/usr/local/bin" > /etc/profile.d/path_fix.sh
  1gb-memory:
    providers:
      - type: virtualbox
        customize:
          - [modifyvm, !ruby/sym id, '--memory', 1024]
      - type: vmware_fusion
        vmx:
          memsize: 1024
  2gb-memory:
    providers:
      - type: virtualbox
        customize:
          - [modifyvm, !ruby/sym id, '--memory', 2048]
      - type: vmware_fusion
        vmx:
          memsize: 2048
  pe-forward-console:
    forwarded_ports:
      - {guest: 443, host: 4443, auto_correct: true}
  windows:
    guest: windows
    communicator: winrm
    forwarded_ports:
      - {guest: 3389, host: 3389, auto_correct: true, id: rdp}
    providers:
      - type: virtualbox
        # must disable clipboard on 4.3.16 or else deal with major corruption!
        # https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm-other
        customize:
          - [modifyvm, !ruby/sym id, '--clipboard', 'disabled']
          # - [modifyvm, !ruby/sym id, '--natdnshostresolver1', 'on']
          - [modifyvm, !ruby/sym id, '--audio', 'none']
          - [modifyvm, !ruby/sym id, '--usb', 'off']
    provisioners:
      # necessary for boxes that don't have RDP enabled
      - {type: shell, path: './config/enable-rdp.bat'}
      - {type: shell, path: './config/install-certs.ps1'}
